<?php

return [
    //English
    'text_1' => 'Welcome to American Kryptos Bank! This is a User Agreement between you (also referred to herein as “Client,” “User,” or customer) and American Time Holding LLC. “American Kryptos Bank”). This User Agreement (“Agreement”) governs your use of the services provided by American Time Holding LLC described below (“American Kryptos Bank Services” or “Services”). By signing up to use an account through.',
    'text_2' => 'www.americankryptosbank.com APIs, or the American Kryptos Bank mobile application (collectively the “American Kryptos Bank Site”), you agree that you have read, understand, and accept all of the terms and conditions contained in this Agreement including Section 7.2.”Arbitration; Waiver of Class Action”, as well as our Privacy Policy, Cookie Policy, and E-Sign Consent Policy.',
    'text_3' => 'As with any asset, the value of Digital Currencies can go up or down and there can be a substantial risk that you lose money buying, selling, holding, or investing in digital currencies. You should carefully consider whether trading or holding Digital Currencies is suitable for you in light of your financial condition. American Kryptos Bank is not registered with the U.S. Securities and Exchange Commission and does not offer securities services in the United States or to U.S. persons.',
    'title_1' => 'PART 1: GENERAL USE',
    'sub_title_1' => '1. Account Setup',
    'list_1' => '1.1. Eligibility.',
    'list_1_text' => ' To be eligible to use the American Kryptos Bank Services, you must be at least 18 years old.',
    'list_2' => '1.2. Terms.',
    'list_2_text' => ' We may amend or modify this Agreement at any time by posting the revised agreement on the American Kryptos Bank Site and/or providing a copy to you (a “Revised Agreement”). The Revised Agreement shall be effective as of the time it is posted but will not apply retroactively. Your continued use of the Services after the posting of a Revised Agreement constitutes your acceptance of such Revised Agreement. If you do not agree with any such modification, your sole and exclusive remedy is to terminate your use of the Services and close your account.',
    'list_3' => '1.3. Registration of American Kryptos Bank Account.',
    'list_3_text' => ' You must register for a American Kryptos Bank account to use the American Kryptos Bank Services (a “American Kryptos Bank Account”). By using a American Kryptos Bank Account you agree and represent that you will use American Kryptos Bank only for yourself, and not on behalf of any third party, unless you have obtained prior approval from American Kryptos Bank. You are fully responsible for all activity that occurs under your American Kryptos Bank Account. We may, in our sole discretion, refuse to open a American Kryptos Bank Account, or limit the number of American Kryptos Bank Accounts that you may hold or suspend or terminate any American Kryptos Bank Account or the trading of specific Digital Currency in your account.',
    'list_4' => '1.4. Identity Verification.',
    'list_4_text' => ' During registration for your American Kryptos Bank Account, you agree to provide us with the information we request for the purposes of identity verification and the detection of money laundering, terrorist financing, fraud, or any other financial crimes and permit us to keep a record of such information. You will need to complete certain verification procedures before you are permitted to use the American Kryptos Bank Services. Your access to one or more American Kryptos Bank Services and the limits that apply to your use of the American Kryptos Bank Services, may be altered as a result of information collected about you on an ongoing basis. The information we request may include certain personal information, including, but not limited to, your name, address, telephone number, e-mail address, date of birth, taxpayer identification number, a government identification, and information regarding your bank account (such as the name of the bank, the account type, routing number, and account number) and in some cases (where permitted by law), special categories of personal data, such as your biometric information. In providing us with this or any other information that may be required, confirm that the information is accurate and authentic. You agree to keep us updated if any of the information you provide changes. You authorize us to make inquiries, whether directly or through third parties, that we consider necessary to verify your identity or protect you and/or us against fraud or other financial crime, and to take action we reasonably deem necessary based on the results of such inquiries. When we carry out these inquiries, you acknowledge and agree that your personal information may be disclosed to credit reference and fraud prevention or financial crime agencies and that these agencies may respond to our inquiries in full. This is an identity check only and should have no adverse effect on your credit rating. Further, you authorize your wireless operator (AT&T, Sprint, T-Mobile, US Cellular, Verizon, or any other branded wireless operator) to use your mobile number, name, address, email, network status, customer type, customer role, billing type, mobile device identifiers (IMSI and IMEI) and other subscriber status details, if available, solely to allow verification of your identity and to compare information you have provided to American Kryptos Bank with your wireless operator account profile information for the duration of the business relationship. See our Privacy Policy for how we treat your data.',
    'list_5' => '1.5. Access.',
    'list_5_text' => ' To access the America Kryptos Bank Services, you must have the necessary equipment (such as a smartphone or laptop) and the associated telecommunication service subscriptions toaccess the Internet. The America Kryptos Bank Services Services can be accessed directly using the America Kryptos Bank Services Site. Access to America Kryptos Bank Services  Services may become degraded or unavailable during times of significant volatility or volume. This could result in the inability to buy or sell for periods of time and may also lead to support response time delays. Although we strive to provide you with excellent service, we do not represent that the America Kryptos Bank Services Site or other America Kryptos ank Services Services will be available without interruption and we do not guarantee that any order will be executed, accepted, recorded, or remain open. America  kryptos Bank Services shall not be liable for any losses resulting from or arising out of transaction delays.',


];
